// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessions() {
  return window['go']['main']['App']['ClearSessions']();
}

export function CompareSessions(arg1, arg2) {
  return window['go']['main']['App']['CompareSessions'](arg1, arg2);
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetSessionCurl(arg1) {
  return window['go']['main']['App']['GetSessionCurl'](arg1);
}

export function GetSessionDetails(arg1) {
  return window['go']['main']['App']['GetSessionDetails'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function Replay(arg1) {
  return window['go']['main']['App']['Replay'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
