// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessions():Promise<void>;

export function CompareSessions(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetSessionCurl(arg1:string):Promise<string>;

export function GetSessionDetails(arg1:string):Promise<Record<string, any>>;

export function GetSessions():Promise<Array<Record<string, any>>>;

export function Replay(arg1:string):Promise<void>;

export function SearchSessions(arg1:Record<string, any>):Promise<Array<Record<string, any>>>;

export function StartProxy(arg1:number,arg2:boolean):Promise<void>;

export function StopProxy():Promise<void>;
